version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:passer@localhost:5432/viago?schema=public
      - REDIS_URL=localhost:6379
    depends_on:
      - postgres
      - redis
    networks:
      - viago-server

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: viago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viago-server

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - viago-server

volumes:
  postgres_data:
  redis_data:

networks:
  viago-server:
    driver: bridge
