packages:
  - apps/**
  - '!apps/erd'
  - packages/**
  - packages/design-system/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - react-native-inappbrowser-reborn
  - react-native-nitro-modules
  - sharp
