import { FontSizes, Fonts } from '@repo/design-system/mobile/utils/fonts';
import { Colors } from '@repo/shared';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  floatingBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 10,
  },
  barSurface: {
    borderRadius: 28,
    backgroundColor: Colors.BACKGROUND,
    overflow: 'hidden',
    shadowColor: Colors.PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  barContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'relative',
  },
  progressBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: `${Colors.PRIMARY}15`,
    borderRadius: 32,
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 18,
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 1,
  },
  timerText: {
    fontFamily: Fonts.semiBold,
    color: Colors.PRIMARY,
    fontSize: FontSizes.md,
  },
  subTimerText: {
    color: Colors.SECONDARY,
    fontSize: 12,
  },
  iconContainerAlt: {
    backgroundColor: Colors.ACCENT,
  },
  bigTimerLabel: {
    color: Colors.SECONDARY,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontSize: 12,
    fontFamily: Fonts.semiBold,
  },
  bigSmartTime: {
    fontFamily: Fonts.bold,
    color: Colors.PRIMARY,
    fontSize: 32,
    marginBottom: 8,
  },
  departureTimeSub: {
    color: Colors.SECONDARY,
    marginTop: 4,
    backgroundColor: `${Colors.PRIMARY}08`,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
  },
  actionBox: {
    backgroundColor: `${Colors.PRIMARY}08`,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  actionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  actionTitle: {
    color: Colors.PRIMARY,
    fontFamily: Fonts.bold,
    textTransform: 'uppercase',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  actionDescription: {
    color: Colors.SECONDARY,
    fontFamily: Fonts.semiBold,
    marginBottom: 4,
  },
  actionSub: {
    color: Colors.ACCENT,
    fontFamily: Fonts.medium,
    fontSize: FontSizes.xs,
  },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 16,
    backgroundColor: `${Colors.PRIMARY}10`,
    zIndex: 1,
  },
  expandText: {
    color: Colors.PRIMARY,
    fontFamily: Fonts.semiBold,
    fontSize: FontSizes.sm,
  },
  centeredContainer: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
    padding: 24,
  },
  cardSurface: {
    backgroundColor: Colors.BACKGROUND,
    borderRadius: 24,
    padding: 20,
    width: '100%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  cardHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerIcon: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: `${Colors.PRIMARY}12`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontFamily: Fonts.regular,
    color: Colors.PRIMARY,
    fontSize: FontSizes.lg,
    flex: 1,
  },
  closeButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: Colors.BACKGROUND,
  },
  bigTimerContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  timerGradient: {
    backgroundColor: `${Colors.ACCENT}08`,
    paddingVertical: 24,
    paddingHorizontal: 24,
    borderRadius: 24,
    width: '100%',
    alignItems: 'center',
    borderColor: Colors.CARD,
    shadowColor: Colors.CARD,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  bigTimer: {
    fontFamily: Fonts.semiBold,
    color: Colors.PRIMARY,
    fontVariant: ['tabular-nums'],
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 42,
    letterSpacing: 1,
  },
  timerSeparator: {
    opacity: 0.5,
  },
  progressSection: {
    marginBottom: 20,
    gap: 10,
  },
  progressTrack: {
    height: 4,
    backgroundColor: Colors.BACKGROUND,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors.PRIMARY,
    borderRadius: 2,
  },
  progressText: {
    textAlign: 'center',
    color: Colors.SECONDARY,
    fontStyle: 'italic',
  },
  detailsContainer: {
    gap: 14,
    marginBottom: 10,
    padding: 0,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: `${Colors.PRIMARY}08`,
    padding: 12,
    borderRadius: 16,
  },
  detailIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.BACKGROUND,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.PRIMARY,
  },
  detailContent: {
    flex: 1,
    gap: 2,
    justifyContent: 'center',
    minHeight: 36,
  },
  detailLabel: {
    color: Colors.SECONDARY,
    fontFamily: Fonts.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontSize: 10,
  },
  detailValue: {
    color: Colors.PRIMARY,
    fontFamily: Fonts.bold,
    fontSize: 15,
  },
  // Active / Zero State Styles
  barSurfaceActive: {
    // shadowColor: Colors.PRIMARY,
    // shadowOpacity: 0.3,
  },
  iconContainerActive: {
    backgroundColor: Colors.BACKGROUND,
  },
  timerTextActive: {
    color: Colors.BACKGROUND,
  },
  subTimerTextActive: {
    color: 'rgba(255,255,255,0.8)',
  },
  expandButtonActive: {
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  expandTextActive: {
    color: Colors.BACKGROUND,
  },
  timerGradientActive: {
    backgroundColor: Colors.PRIMARY,
    borderColor: Colors.PRIMARY,
  },
  bigTimerLabelActive: {
    color: 'rgba(255,255,255,0.8)',
  },
  bigSmartTimeActive: {
    color: Colors.BACKGROUND,
  },
  departureTimeSubActive: {
    color: 'rgba(255,255,255,0.9)',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  fillOverlay: {
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
});
